### PR TITLE
update all pins

### PR DESCRIPTION
**Pull request by wolfv**
@Tobias-Fischer @traversaro I will also run a larger comparison against the current conda-forge pinnings.

Do you have anything in mind that we should also update here? 
I think the easiest might be a full rebuild of everything ... 

We could also go for Python 3.10 – we lose the ability to install ros-noetic / ros-galactic in the same environment but I think that's OK. What do you think?

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I think we should still go for py39, there's too many missing py310 packages. There's quite a few migrations which are basically done in conda-forge (we should close out some of them). I'd say if we go through the hassle of rebuilding we should as well incorporate those. And if we do it here, we can sync with noetic.

**Comment by Tobias-Fischer** [comment]
Candidates: assimp, gdal, icu, libprotobuf, occt, proj

**Comment by traversaro** [comment]
For assimp, I would bypass conda-forge-pinnings and pin assimp to 5.2.4 . The migration to assimp 5.2.4 is almost done (see https://conda-forge.org/status/#assimp524), and just the `hpp-*` packages are missing, but those do not have any assimp=5.2.3 packages either.

**Comment by wolfv** [comment]
Thanks for all the notes! 

I think one downside of not going to Python 3.10 is that 3.10 is the default version on Ubuntu 22.04 (which is the distro that humble is released on), so ROS users might expect to be able to use 3.10 features.

**Comment by wolfv** [comment]
I went with the migrations for:

- qt -> qt_main 5.15
- icu
- proj
- libffi
- ~gdal~ (already done in cf)

I decided against:

- protobuf -> ONNX isn't rebuilt and there is some bug with it, it seems relevant to robotics so I went with the older protobuf (https://github.com/conda-forge/onnxruntime-feedstock/pull/32)
- openssl -> I think the migration isn't complete enough yet, especially the `cryptography` Python package hasn't been rebuilt yet
- occt (doesn't seem to be used in ROS)

**Comment by wolfv** [comment]
lets see how this goes! :) 🚀

**Pull request merged**
