### PR TITLE
[DRAFT] Add ros_gz package

### PR DESCRIPTION
**Pull request by mkarklins**
This adds the `ros_gz` package. 

Was able to successfully build locally on macOS. Still want to run some tests with it to ensure it actually works.

Closes: https://github.com/RoboStack/ros-humble/issues/68

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks for testing! Could you please also add on the other two platforms?

**Comment by Tobias-Fischer** [comment]
Great. Let me know once you had a chance testing, and I’ll be happy to merge when you are.

**Comment by mkarklins** [comment]
Actually I'm struggling a bit here, perhaps you can help out a bit. 

- There are already are `ros_gz` sub-packages available in the channels e.g. `https://anaconda.org/robostack-staging/ros-humble-ros-gz` and `https://anaconda.org/robostack-humble/ros-humble-ros-gz-bridge`. Looks like those have been built against Gazebo Ignition - as such those don't work with Garden. Where did these package originate from? 

- When I try to build the `ros_gz` metapackage I noticed something interesting. During `boa build` it downloads the source code and checks it out to tag `release/humble/ros_gz/0.244.11-1` - where the latest commit is `Trimmed the branch to only the ros_gz sub directory`, looks like that comes from the release tool: `https://github.com/ros-infrastructure/bloom` and that tag only contains 4 files from here: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz - `ros_gz` is a meta package. So, `boa build` doesn't do anything useful - you can see the build log here: https://github.com/RoboStack/ros-humble/actions/runs/5199049780/jobs/9381639707?pr=72#step:17:2478

- To re-iterate if we want to build against Gazebo Garden we need to set the `GZ_VERSION` env variable to `garden` during compile time. You mentioned: `By the way, I can’t recall how exactly vinca parses the package.xml, and I’m not sure if it would respect the environment variables. In the past I’ve simply remapped within the robostack.yaml /conda.yaml to whichever gazebo version I want.` - I suppose I'm not exactly sure how to do that? 

Sorry, for all of the questions. I'm quite eager to understand how this works and contribute, but I'm a bit over my head here :)

**Comment by mkarklins** [comment]
@Tobias-Fischer I hope I understand correctly - the issue is that to install a "metapackage" a custom configuration is needed. I can't seem to find a previous example of such a package.

**Comment by traversaro** [comment]
> @Tobias-Fischer I hope I understand correctly - the issue is that to install a "metapackage" a custom configuration is needed. I can't seem to find a previous example of such a package.

I guess there is nothing special about metapackages, they just install their package.xml and other metadata files, and then they just depend on the other packages that actually contains something. See https://github.com/ros-planning/moveit2/blob/main/moveit/CMakeLists.txt for an example of a metapackage that seems to be working fine: https://anaconda.org/robostack-staging/ros-humble-moveit/files .

**Comment by mkarklins** [comment]
> I guess there is nothing special about metapackages, they just install their package.xml and other metadata files, and then they just depend on the other packages that actually contains something. See https://github.com/ros-planning/moveit2/blob/main/moveit/CMakeLists.txt for an example of a metapackage that seems to be working fine: https://anaconda.org/robostack-staging/ros-humble-moveit/files .

Hmm - if I look at the build log here: https://github.com/RoboStack/ros-humble/actions/runs/5290691692/job/14323454264?pr=72#step:15:713 - I don't see any of the source files or sub-packages being built. Looks like it's just building the meta files and that's it. Could it be that the GH actions pipeline needs to be updated?

**Comment by Tobias-Fischer** [comment]
Hi @mkarklins - apologies for the confusion.
- Basically, as the ros-humble-ros-gz dependencies already exist, our `vinca` tool does not pick them up again _unless_ if they are added explicitly to the vinca_*.yaml files.
- The alternative is to set `full_rebuild` to `true` and bump the `build_number`, but this would rebuild _all_ packages, which is probably not what you want. 
- So you would need to add these packages to the vinca_*.yaml files (and potentially some of their dependencies): 
https://github.com/gazebosim/ros_gz/blob/07f8adc62f9ac009d9054c88a3e5706eab9f65ed/ros_gz/package.xml#L17C16-L20 (or, looking at it, it might be better to go by this list: https://github.com/gazebosim/ros_gz/tree/humble but ignore the ros_ign* ones as they are just shim packages for the ros_gz* packages).

Now, by default, these packages pull in Fortress (see e.g. https://github.com/gazebosim/ros_gz/blob/4a5972bc6c1bcd2797a023ce934e6ef4d8e08de9/ros_gz_image/package.xml#L22-L23). As far as I know, there is no (easy?) way to pass GZ_VERSION to our vinca tool (I don't think we ever implemented these conditions).
- The proper way would be to expand vinca to digest these conditions.
- The hacky way is to look at the mappings. In the above example, ros-gz-image requests `ignition-msgs8` and `ignition-transport11`. Internally, this is being mapped from ROS packages to conda-forge packages here: https://github.com/RoboStack/ros-humble/blob/8ff5757965351d129d6da9d2004605cc8d6d7af9/robostack.yaml#L136-L163
- We could remap e.g. https://github.com/RoboStack/ros-humble/blob/8ff5757965351d129d6da9d2004605cc8d6d7af9/robostack.yaml#L152-L153 to the Garden version: `gz-msgs9` which also exists on conda-forge (see https://github.com/gazebosim/ros_gz/blob/4a5972bc6c1bcd2797a023ce934e6ef4d8e08de9/ros_gz_image/package.xml#L17 and https://anaconda.org/search?q=gz-msgs). This remapping is done by simply changing the value to `gz-msgs9` for key `ignition-msgs8` in the robostack.yaml (and so forth for the other packages).
- Once that's done, we would need to modify vinca to set the correct `GZ_VERSION` environment variable. We would need to modify https://github.com/RoboStack/vinca/blob/master/vinca/templates/build_ament_cmake.sh.in to check if the `ROS_DISTRO` is set to `humble` and then `export GZ_VERSION="garden"` which is picked up by cmake (see e.g. https://github.com/gazebosim/ros_gz/blob/humble/ros_gz_image/CMakeLists.txt).
- Finally, the package would be ready to be rebuilt ;).

I understand it's quite an involved process, but each individual step should be quite straightforward. Unfortunately I currently don't have the capacity to do these steps myself, but I'd be happy to help out if you get stuck @mkarklins.

**Comment by mkarklins** [comment]
Very much appreciated for your reply! 

> Unfortunately I currently don't have the capacity to do these steps myself, but I'd be happy to help out if you get stuck @mkarklins.

All good! I should be able to do this myself, will report back with progress.

**Comment by Tobias-Fischer** [comment]
We have this for most platforms now, and Windows is tracked in #146

**Pull request closed without merging**
