### PR TITLE
Add rosbridge suite

### PR DESCRIPTION
**Pull request by b1n-ch1kn**
Used for a web hosted rviz-like interface https://github.com/b1n-ch1kn/vizanti/tree/ros2

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
We should add this on all platforms

**Comment by b1n-ch1kn** [comment]
Looks like binaries for either macos haven't been published. Although osx-64 somehow got `actuator_msgs` and linux-64 got `ublox_nav_sat_fix` packages built in that workflow

**Comment by b1n-ch1kn** [comment]
Skipping `nav2-mppi-controller` for now, but I'll likely look into the missing `xtensor` package further (this is one of the nav2 packages I'm looking into)

**Comment by Tobias-Fischer** [comment]
I’m against skipping nav2-mppi-controller - this section is meant for “permanent” skips of packages that should never be built. Let’s look into the underlying problem instead.

**Comment by Tobias-Fischer** [comment]
See also https://github.com/RoboStack/ros-humble/pull/75

**Comment by b1n-ch1kn** [comment]
Seems like a long chain of xtensor->xsimd issues thats now bugging out arm and macos.
Not sure if its an install issue, xsimd and xtensor are installed thru Conda, could it be finding a base install?
I also saw xtensor's latest version is 0.24.6 (https://anaconda.org/conda-forge/xtensor) but is using 0.23.9 to build recipes so there might be a dependency clash

**Pull request merged**
