### PR TITLE
Update github workflow to macOS-11

### PR DESCRIPTION
**Pull request by olivier-stasse**
As macos-10.5 is deprecated this pull request requires macOS-11. This is already this version on buildbranch_osx_arm64.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @olivier-stasse - we need to make this change in vinca, rather than here. What particular issue are you addressing?

**Comment by Tobias-Fischer** [comment]
I think what you really want is changing https://github.com/RoboStack/ros-humble/blob/c3de8e0c24157be702304a0b647ffcd5e6aa4af7/conda_build_config.yaml#L28-L35

**Comment by olivier-stasse** [comment]
> I think what you really want is changing
> 
> https://github.com/RoboStack/ros-humble/blob/c3de8e0c24157be702304a0b647ffcd5e6aa4af7/conda_build_config.yaml#L28-L35

Thanks a lot for the explanations. So my pull request was a wrong answer to the problem.

**Comment by Tobias-Fischer** [comment]
All fixed now

**Pull request closed without merging**
