### PR TITLE
Update localization and slam packages

### PR DESCRIPTION
**Pull request by b1n-ch1kn**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks - looks good. Could you please add a delineator so we know which packages we support currently? Basically in between the currently built packages and those commented out.

**Comment by b1n-ch1kn** [comment]
Sure thing.
The delineator isn't quite accurate as there are a number of supported packages below the delineator, so I [wrote a script](https://github.com/b1n-ch1kn/ros-humble/blob/vinca-sorting/supported.py) that scrapes the github.io package table as a csv and separates packages in the vinca file.
It looks quite nice now: https://github.com/b1n-ch1kn/ros-humble/blob/vinca-sorting/sorted_vinca_linux_64.yaml

**Comment by traversaro** [comment]
Cool! Sorry I missed the comment originally. Probably the easiest thing to do is to make a GitHub Action that is triggered manually that updates those files (as I guess we do not want to have an automatic update)

**Comment by b1n-ch1kn** [comment]
My thoughts too. Would be cool to fully automate the table scraping at some point so there's still some work before its an action.

**Comment by Tobias-Fischer** [comment]
We shouldn’t parse the table and instead rely on the source script: https://github.com/RoboStack/robostack.github.io/blob/master/utils/compare_pkg_completeness.py

We could add a JSON output or something that is trivial to read.

**Pull request merged**
