### PR TITLE
Update to the latest versions of everything

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by traversaro** [comment]
Perhaps we may want to also refresh https://github.com/RoboStack/ros-humble/blob/40de21138ca4ab626447bcbc3e9b3b9846fadf79/.ci_support/conda_forge_pinnings.yaml, in particular libopencv .

**Comment by wolfv** [comment]
@traversaro I agree, but I think that should maybe another run? This one just bumps the versions of all packages that have newer releases in rosdistro :)

**Comment by traversaro** [comment]
Ah, I thought it was a complete rebuild. But if we are updating only the packages that have new versions, should we also recompile the packages that depend on the updated packages, as their ABI could have changed?

**Comment by Tobias-Fischer** [comment]
Agreed @traversaro - I think a full rebuild would be best (and shouldn’t be too bad these days in terms of time investment)

**Comment by Tobias-Fischer** [comment]
See #229

**Pull request closed without merging**
