### PR TITLE
Commit fixes to build mimick_vendor on Windows locally

### PR DESCRIPTION
**Pull request by traversaro**
Debug https://github.com/RoboStack/ros-humble/issues/28 .

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I found that some builds fail in the PRs but build okay on the main branch - feel free to commit there, too.

**Comment by traversaro** [comment]
I was not unable to fix https://github.com/RoboStack/ros-humble/issues/28 . Anyhow, I commit the fixes that were necessary to build the package in https://github.com/RoboStack/ros-humble/pull/21#issuecomment-1345670408 , that are mainly:
* Patch to use FetchContent instead of ExternalProject on Windows: the build is already quite error-prone on Windows, at least we can avoid all the logic of manually forwarding options and parameters by using FetchContent and building mimick directly as part of the mimick_vendor project
* Use the commit corresponding to https://github.com/ros2/Mimick/pull/25

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro - I will see whether this actually builds on the Windows CI first; if not, I will upload your pre-built package.

**Comment by Tobias-Fischer** [comment]
It built fine in CI - thanks so much @traversaro!

**Pull request merged**
