### PR TITLE
add vision-msgs for all platforms

### LINKED ISSUE #83: Package request: vision_msgs_rviz_plugins
### Package name

vision_msgs_rviz_plugins

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

I tend to use the `vision_msgs` package quite frequently in my research, and wanted the RViz plugins to help with visualization (as opposed to boxes drawn by some node I created with a ton of bugs). I saw that the `vision_msgs` package isn't available for platforms other than `linux-64`, and was wondering if someone knows if there are any build issues with these packages I should be aware of.

If there are none, I can try submitting a PR for both `vision_msgs` and `vision_msgs_rviz_plugins` for `linux-64`.

### Links and references (optional)

_No response_

### PR DESCRIPTION
**Pull request by anand-bala**
Fixes #83

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I think there is a double rviz typo

**Comment by anand-bala** [comment]
Oof! Sorry about that. Serves me right for pushing commits just before I have to leave. I'll send an updated commit soon.

**Comment by anand-bala** [comment]
Hey @Tobias-Fischer, since https://github.com/mamba-org/boa/issues/284 blocks `vision-msgs-rviz-plugins` being added, I wonder if it makes sense to just add `vision-msgs` for the other platforms, and deal with `vision-msgs-rviz-plugins` separately?

**Comment by Tobias-Fischer** [comment]
Sure, if that helps you :)

**Pull request merged**
