### PR TITLE
[osx] Add joint_limits  as a package.

### PR DESCRIPTION
**Pull request by olivier-stasse**
This package was compiled successfully on a Mac Ventura 13.4 with robostack humble.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
As for the CI, I had a problem with ```ros-humble-nav2-mppi-controller``` looking for ```xsmid```.
Once ```xsmid``` is installed I run into compilation option problems.
But this would probably need a separate PR ?

**Comment by wolfv** [comment]
Hmm, I don't think this is related to `xsimd` as the compiler error mentions that `-fconcepts` is not supported by `clang-14`.

The `-fconcepts` flag comes from here: https://github.com/ros-planning/navigation2/blob/01b84136493a47c2fe6ffa9d0b1132cbf132b189/nav2_mppi_controller/CMakeLists.txt#L75C1-L80

I'll have a quick look at workarounds.

**Comment by olivier-stasse** [comment]
> Hmm, I don't think this is related to `xsimd` as the compiler error mentions that `-fconcepts` is not supported by `clang-14`.
> 
> The `-fconcepts` flag comes from here: https://github.com/ros-planning/navigation2/blob/01b84136493a47c2fe6ffa9d0b1132cbf132b189/nav2_mppi_controller/CMakeLists.txt#L75C1-L80
> 
> I'll have a quick look at workarounds.

You are right. This is exactly the compilation problem I was referring to. I am afraid that other problems may appear.

**Comment by wolfv** [comment]
I filed an issue upstream: https://github.com/ros-planning/navigation2/issues/3625

It looks like it might be possible to just patch out the line in the CMake file ...

**Comment by b1n-ch1kn** [comment]
Yeah a [small patch](https://github.com/b1n-ch1kn/ros-humble/blob/b6afdffde30880b004f5657245e35c23f868db85/patch/ros-humble-nav2-mppi-controller.osx.patch) worked for the -fconcepts part but ran into other issues with xtensor and xsimd (https://github.com/RoboStack/ros-humble/pull/74#issuecomment-1592193922)

**Comment by Tobias-Fischer** [comment]
Hi @olivier-stasse - could you please provide me with write access to your fork, or alternatively pull in the changes from upstream (here) to your branch?


Many thanks, Tobi

**Comment by olivier-stasse** [comment]
> Hi @olivier-stasse - could you please provide me with write access to your fork, or alternatively pull in the changes from upstream (here) to your branch?
> 
> Many thanks, Tobi

Dear @Tobias-Fischer I did rebase my fork on the main branch.
Thanks for your help.

**Comment by olivier-stasse** [comment]
It is very strange that the rebase is crashing the osx-64 CI...

**Comment by Tobias-Fischer** [comment]
Not sure why, but enforcing a newer version of xtensor seems to solve the issues

/cc @wolfv @b1n-ch1kn @olivier-stasse

**Comment by olivier-stasse** [comment]
Thanks a lot @Tobias-Fischer for the time.

**Pull request merged**
