### PR TITLE
Linux aarch64 - ros_core, ros_base, perception, simulation, desktop, desktop_full

### PR DESCRIPTION
**Pull request by sonelu**
All tested locally and ready to go.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks for this, @sonelu! What's the plan of attack in general? Do you want to try to rebuild all packages that are currently selected?

**Comment by sonelu** [comment]
If you don't have any other strategy you can just let the PRs build. I've created them separately by platform, and I will come with additional PRs for OSX and WIN as I am able to test them locally to reduce the impact on CI.

After this we can add the additional packages as needed. I was thinking to get a python script that pulls the download numbers from Anaconda for packages in robostack-staging and we can tackle them in order of interest.

**Comment by Tobias-Fischer** [comment]
All of the packages that are selected currently have been requested by users, so I'd like to keep them all if possible. The ideal PR would basically just increase the build numbers and update / create new patches if needed :)

**Comment by Tobias-Fischer** [comment]
See #229

**Pull request closed without merging**
