### PR TITLE
Re-include plotjuggler for linux

### PR DESCRIPTION
**Pull request by alistair-english**
Are we able to re-include plotjuggler in the humble build? Seems like it was set up and then excluded last year

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
There is a weird compile error (saying it is not compiled with C++11 despite the flags for C++11/17 are passed) - not sure what's going on. Can you take a look @alistair-english to see if you can figure it out? Don't have the bandwidth for debugging at the moment ..

**Comment by alistair-english** [comment]
> There is a weird compile error (saying it is not compiled with C++11 despite the flags for C++11/17 are passed) - not sure what's going on. Can you take a look @alistair-english to see if you can figure it out? Don't have the bandwidth for debugging at the moment ..

Yep will do

**Comment by Tobias-Fischer** [comment]
Got it to work @alistair-english - what a pain :P

**Comment by andersdu** [comment]
hello, awesome, I was looking for it. How can I install it to my MacOS? also would it be added to ros_noetic? thanks.

**Comment by andersdu** [comment]
I'm not familiar with these setups at all, sorry could not help with that.
What I could tell the the plotjuggler project did compile and works on my OSX ARM64 laptop, I'm using master branch and the latest commit is 95ff88f08d0fe2c108a3e149c2b8ed3bbfc092fb.
One thing I found in the failure on #58 is: in my laptop the plotjuggler_base is compiled as static library, and it seems in the PR it's compiled as shared lib and it failed there?

**Comment by Tobias-Fischer** [comment]
This works now @andersdu

**Pull request merged**
