### PR TITLE
Use vendored ogre & fix python install location

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Full rebuild of all platforms to Unix python install location https://github.com/RoboStack/ros-humble/issues/41 and Gazebo issues https://github.com/RoboStack/ros-humble/issues/24

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@traversaro - can you see what's wrong with the Windows build? I can't see the actual error that occurs ..

**Comment by traversaro** [comment]
> @traversaro - can you see what's wrong with the Windows build? I can't see the actual error that occurs ..

I think the actual Windows error is:
~~~
2023-02-04T10:51:21.1369691Z The input line is too long.
2023-02-04T10:51:21.1370054Z The syntax of the command is incorrect.
~~~
in my experience, this happens one a environment variable (such as `PATH`) is too long, so if it is used in a command the resulting command is too long (~8191 char,see https://learn.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation). It happens quite frequently if you activate several times the same environment, especially if the `vcvars.bat` if sourced every time. However, I am not sure what it is the offending command/env variable in this case.

**Comment by Tobias-Fischer** [comment]
I'm out of ideas here .. I am not able to set the path consistently across different steps :(. I remember you played with this before @wolfv?

**Comment by Tobias-Fischer** [comment]
This seems to be fine - I'll merge it, will fix the Windows issues separately.

**Pull request merged**
