### PR TITLE
apriltag library for humble

### PR DESCRIPTION
**Pull request by christianrauch**
Requires:
- [x] downgrade of glibc version: https://github.com/RoboStack/vinca/pull/45

### CODE REVIEW

**Comment by christianrauch** [comment]
The CI is showing the error `Could not find output with name ros2-distro-mutex` but locally, this works for me. Any ideas?

**Comment by christianrauch** [comment]
When I build locally (I have to downgrade packages via `micromamba install boa=0.15 ruamel.yaml=0.17` for this) without my previous vinca workaround (https://github.com/RoboStack/vinca/pull/45) of downgrading glibc from 2.17 to 2.12, I again get packages that cannot be resolved:
```
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - gxx_linux-64 11*
 - gcc_linux-64 11*
 - sysroot_linux-64 2.17.*
 - ninja
 - setuptools
 - make
 - coreutils
 - cmake
 - cython
 - mesa-libgl-devel-cos6-x86_64
 - mesa-dri-drivers-cos6-x86_64
 - libselinux-cos6-x86_64
 - libxdamage-cos6-x86_64
 - libxxf86vm-cos6-x86_64
 - libxfixes-cos6-x86_64
 - libxext-cos6-x86_64
 - libxau-cos6-x86_64
 - libxcb-cos6-x86_64

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package mesa-libgl-devel-cos6-x86_64-11.0.7-h1795305_1101 requires 
sysroot_linux-64 2.12.*, but none of the providers can be installed
```

The build works locally with https://github.com/RoboStack/vinca/pull/45 (downgrade glibc from 2.17 to 2.12).

@Tobias-Fischer Can it be that there is another conflicting workaround in `vinca`? I noticed two "OPENGL" and "GL" workarounds in vinca: https://github.com/RoboStack/vinca/blob/ac21942ffc773217bee5c754dd89667a0f5effae/vinca/main.py#L439-L488 where "fix up OPENGL support for Unix" is adding the package `{{ cdt('mesa-libgl-devel') }}`.

**Comment by Tobias-Fischer** [comment]
> The CI is showing the error `Could not find output with name ros2-distro-mutex` but locally, this works for me. Any ideas?

I'm now running into this issue locally, with `boa 0.16`. I suspect this is the culprit. @christianrauch - could you please let me know which version of boa you have installed locally?

/cc @wolfv - could you please take a look

**Comment by christianrauch** [comment]
> @christianrauch - could you please let me know which version of boa you have installed locally?

Locally I am running 0.15.1.

**Comment by Tobias-Fischer** [comment]
These have been added :)

**Pull request closed without merging**
