### PR TITLE
add RealSense library and driver node

### PR DESCRIPTION
**Pull request by christianrauch**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @christianrauch - many thanks for your contribution and apologies that things are a bit broken at the moment, hopefully I’ll find some time soon to fix things up.

The issue we face here can be resolved as such: https://github.com/conda-forge/cdt-builds/issues/41

this needs to be changed in vinca I think

**Comment by christianrauch** [comment]
I am trying to understand how these dependencies on `libudev-cos7-x86_64` and `libudev-devel-cos7-x86_64` are generated and where they are supposed to be. So far, I can only find the "cos6" variants of the dependencies:
- `libudev-cos6-x86_64`: https://anaconda.org/conda-forge/libudev-cos6-x86_64
- `libudev-devel-cos6-x86_64`: https://anaconda.org/conda-forge/libudev-devel-cos6-x86_64

Can we not use those "cos6" variants of the dependencies to satisfy `libudev` and `libudev-devel`?

**Comment by christianrauch** [comment]
I was able to build locally by downgrading the glibc and "cos" versions to 2.12 and 6, respectively. This requires https://github.com/RoboStack/vinca/pull/45, i.e. you have to run `pip install git+https://github.com/christianrauch/vinca.git@glibc2.12 --no-deps` when following the official instructions.

**Comment by Tobias-Fischer** [comment]
I think the better way to go is simply removing https://github.com/RoboStack/vinca/blob/fead8d0e77cef87d4099ccc68f827914123d7f3a/vinca/main.py#L439-L447 as this is not required anymore for cos7.

**Comment by Tobias-Fischer** [comment]
See https://github.com/RoboStack/vinca/commit/ac21942ffc773217bee5c754dd89667a0f5effae

**Comment by christianrauch** [comment]
@Tobias-Fischer Thanks. I removed the "cos6" entry. Can you approve my workflow so I can test this on the CI again?

**Comment by christianrauch** [comment]
Could someone help me out with the CI error `RuntimeError: Could not find output with name ros2-distro-mutex` here: https://github.com/RoboStack/ros-humble/actions/runs/7334369039/job/19971187944?pr=117? I can see that the package `ros2-distro-mutex` is available on `robostack-staging`. Does the CI pipeline have to install this manually?

**Comment by christianrauch** [comment]
Is this now obsoleted by https://github.com/RoboStack/ros-humble/pull/129?

**Comment by Tobias-Fischer** [comment]
Yes :)

**Pull request closed without merging**
